"""phase3_collab_portal

Phase 3 adds ROI input stubs (hours_saved_per_month, cost_savings_per_month, revenue_impact).
Phase 4 will add full ROI-01 computed fields (weekly_cost, yearly_cost, etc.) in a separate migration.

Also adds: ticket_comments, ticket_subtasks, ticket_templates tables;
attachment stub columns (attachment_filename, attachment_size_bytes) on tickets.

Revision ID: 93dab7e5b92c
Revises: e58d6c737dab
Create Date: 2026-02-25 10:43:01.958170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93dab7e5b92c'
down_revision: Union[str, None] = 'e58d6c737dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('problem_statement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_urgency', sa.Integer(), nullable=True),
    sa.Column('default_effort_estimate', sa.Float(), nullable=True),
    sa.Column('default_next_step', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ticket_templates_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_templates'))
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_comments_author_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments'))
    )
    op.create_table('ticket_subtasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_subtasks_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_subtasks'))
    )
    op.add_column('tickets', sa.Column('hours_saved_per_month', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('cost_savings_per_month', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('revenue_impact', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('attachment_filename', sa.String(length=500), nullable=True))
    op.add_column('tickets', sa.Column('attachment_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'attachment_size_bytes')
    op.drop_column('tickets', 'attachment_filename')
    op.drop_column('tickets', 'revenue_impact')
    op.drop_column('tickets', 'cost_savings_per_month')
    op.drop_column('tickets', 'hours_saved_per_month')
    op.drop_table('ticket_subtasks')
    op.drop_table('ticket_comments')
    op.drop_table('ticket_templates')
    # ### end Alembic commands ###
