"""phase5_advanced_features

Revision ID: 9c6cd841fe34
Revises: 13444529af83
Create Date: 2026-02-25 14:30:14.214863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c6cd841fe34'
down_revision: Union[str, None] = '13444529af83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_defs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'date', name='fieldtype'), nullable=False),
    sa.Column('scope', sa.Enum('workspace', 'personal', name='fieldscope'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'personal' AND owner_id IS NOT NULL) OR (scope = 'workspace' AND owner_id IS NULL)", name=op.f('ck_custom_field_defs_ck_custom_field_defs_scope_owner')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_custom_field_defs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_defs'))
    )
    op.create_table('saved_filters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filter_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_filters_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_filters'))
    )
    op.create_table('sprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sprints_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints'))
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_wiki_pages_created_by_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['wiki_pages.id'], name=op.f('fk_wiki_pages_parent_id_wiki_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages'))
    )
    op.create_table('ticket_dependencies',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['tickets.id'], name=op.f('fk_ticket_dependencies_blocked_id_tickets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['tickets.id'], name=op.f('fk_ticket_dependencies_blocker_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id', name=op.f('pk_ticket_dependencies'))
    )
    op.add_column('tickets', sa.Column('sprint_id', sa.Uuid(), nullable=True))
    op.add_column('tickets', sa.Column('wiki_page_id', sa.Uuid(), nullable=True))
    op.add_column('tickets', sa.Column('custom_field_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(op.f('fk_tickets_sprint_id_sprints'), 'tickets', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_wiki_page_id_wiki_pages'), 'tickets', 'wiki_pages', ['wiki_page_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tickets_wiki_page_id_wiki_pages'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_sprint_id_sprints'), 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'custom_field_values')
    op.drop_column('tickets', 'wiki_page_id')
    op.drop_column('tickets', 'sprint_id')
    op.drop_table('ticket_dependencies')
    op.drop_table('wiki_pages')
    op.drop_table('sprints')
    op.drop_table('saved_filters')
    op.drop_table('custom_field_defs')
    # ### end Alembic commands ###
