"""drop_sprints_table_and_sprint_id

Revision ID: 61b4cd2c3e5e
Revises: 9c6cd841fe34
Create Date: 2026-02-25 15:25:45.952338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b4cd2c3e5e'
down_revision: Union[str, None] = '9c6cd841fe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop FK and column on tickets first, then drop the sprints table
    op.drop_constraint(op.f('fk_tickets_sprint_id_sprints'), 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'sprint_id')
    op.drop_table('sprints')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sprint_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tickets_sprint_id_sprints'), 'tickets', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sprints_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints'))
    )
    # ### end Alembic commands ###
