"""phase2_kanban_core

Revision ID: e58d6c737dab
Revises: bc1748a61656
Create Date: 2026-02-25 07:31:25.980615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e58d6c737dab'
down_revision: Union[str, None] = 'bc1748a61656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('problem_statement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('effort_estimate', sa.Float(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority_enum'), nullable=True),
    sa.Column('status_column', sa.Enum('Backlog', 'Discovery', 'In Progress', 'Review/QA', 'Done', name='status_column_enum'), server_default='Backlog', nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('urgency >= 1 AND urgency <= 5', name=op.f('ck_tickets_ck_tickets_urgency')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_tickets_department_id_departments')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tickets_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_table('column_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('column', sa.String(length=100), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_column_history_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_column_history'))
    )
    op.create_index('ix_column_history_ticket_exited', 'column_history', ['ticket_id', 'exited_at'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ticket_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_events_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_index('ix_ticket_events_ticket_created', 'ticket_events', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_created', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index('ix_column_history_ticket_exited', table_name='column_history')
    op.drop_table('column_history')
    op.drop_table('tickets')
    # ### end Alembic commands ###
